# Generated by Django 5.0.3 on 2024-05-31 19:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Saver',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('user_number', models.IntegerField()),
                ('NIN', models.CharField(max_length=14)),
                ('contact', models.IntegerField()),
                ('email', models.EmailField(max_length=254)),
                ('profile_photo', models.ImageField(upload_to='')),
                ('location', models.CharField(max_length=100)),
                ('nok', models.CharField(max_length=100)),
            ],
        ),
    ]
