# Generated by Django 5.0.7 on 2024-08-12 09:42

import django.core.validators
import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Member',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, validators=[django.core.validators.RegexValidator(message='Enter both names, no special characters', regex="^(?=.{1,100}$)[A-Za-z]+(?:[\\'\\s-][A-Za-z]+)* [A-Za-z]+(?:[\\'\\s-][A-Za-z]+)*$")])),
                ('user_number', models.IntegerField(blank=True, null=True)),
                ('NIN', models.CharField(db_index=True, max_length=14, unique=True)),
                ('contact', models.CharField(max_length=13, validators=[django.core.validators.MinLengthValidator(10), django.core.validators.RegexValidator(message='Enter a valid Country contact', regex='^(\\+256|0)\\d{9}$')])),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('profile_photo', models.ImageField(blank=True, null=True, upload_to='uploads')),
                ('location', models.CharField(max_length=100)),
                ('gender', models.CharField(choices=[('Male', 'Male'), ('Female', 'Female')], max_length=10)),
                ('next_of_kin', models.CharField(max_length=100, validators=[django.core.validators.RegexValidator(message='Enter both names, no special characters', regex="^(?=.{1,100}$)[A-Za-z]+(?:[\\'\\s-][A-Za-z]+)* [A-Za-z]+(?:[\\'\\s-][A-Za-z]+)*$")])),
                ('date_of_registration', models.DateField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Save',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_number', models.IntegerField()),
                ('amount', models.PositiveIntegerField(default=0, validators=[django.core.validators.MinValueValidator(10000)])),
                ('save_time', models.TimeField(auto_now_add=True)),
                ('identity', models.UUIDField(blank=True, default=uuid.uuid4, unique=True)),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='member', to='savingsApp.member')),
            ],
        ),
        migrations.CreateModel(
            name='Loan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount_borrowed', models.PositiveIntegerField(default=0, validators=[django.core.validators.MinValueValidator(10000)])),
                ('loan_date', models.DateTimeField(auto_now_add=True)),
                ('witness', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='savingsApp.member')),
                ('reciever', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='savingsApp.save')),
            ],
        ),
    ]
