# Generated by Django 5.0.3 on 2024-06-07 12:01

import datetime
import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('savingsApp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='member',
            name='profile_photo',
            field=models.ImageField(upload_to='uploads'),
        ),
        migrations.CreateModel(
            name='Loan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount_borrowed', models.PositiveIntegerField(default=0, validators=[django.core.validators.MinValueValidator(10000)])),
                ('loan_date', models.DateField(default=datetime.datetime.now)),
                ('reciever', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='savingsApp.save')),
                ('witness', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='savingsApp.member')),
            ],
        ),
    ]
