# Generated by Django 5.0.7 on 2024-08-12 13:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('savingsApp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='member',
            name='profile_photo',
            field=models.ImageField(upload_to='uploads'),
        ),
        migrations.AlterField(
            model_name='member',
            name='user_number',
            field=models.IntegerField(default=1, unique=True),
            preserve_default=False,
        ),
    ]
