# Generated by Django 5.0.3 on 2024-05-31 19:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('savingsApp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='saver',
            old_name='nok',
            new_name='next_of_kin',
        ),
    ]
