# Generated by Django 5.0.3 on 2024-05-31 19:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('savingsApp', '0002_rename_nok_saver_next_of_kin'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Saver',
            new_name='Member',
        ),
    ]
