# Generated by Django 5.0.3 on 2024-05-31 20:29

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('savingsApp', '0003_rename_saver_member'),
    ]

    operations = [
        migrations.AlterField(
            model_name='member',
            name='contact',
            field=models.CharField(max_length=13, validators=[django.core.validators.MinLengthValidator(10), django.core.validators.RegexValidator(message='Enter a valid Country contact', regex='^(\\+256|0)\\d{9}$')]),
        ),
        migrations.AlterField(
            model_name='member',
            name='name',
            field=models.CharField(max_length=100, validators=[django.core.validators.RegexValidator(message='Enter both names, no special characters', regex="^(?=.{1,100}$)[A-Za-z]+(?:[\\'\\s-][A-Za-z]+)* [A-Za-z]+(?:[\\'\\s-][A-Za-z]+)*$")]),
        ),
    ]
