# Generated by Django 5.0.3 on 2024-05-31 21:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('savingsApp', '0004_alter_member_contact_alter_member_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='member',
            name='NIN',
            field=models.CharField(max_length=14, unique=True),
        ),
        migrations.AlterField(
            model_name='member',
            name='profile_photo',
            field=models.ImageField(upload_to='uploads'),
        ),
        migrations.AlterField(
            model_name='member',
            name='user_number',
            field=models.IntegerField(unique=True),
        ),
    ]
